
version: '3.5'

services:
  app:
    build: .
    container_name: draw_chart
    working_dir: /usr/src/app
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app
      - app:/usr/src/app/node_modules
    command: npm start

volumes:
  app:
